<script setup lang="ts">
// The guided form for a document or file read through a DuckDB extension: a
// PDF, a web page, a file at a URL, and a file in Google Drive.
//
// One address, one "Read as" picker, one table name. The reader function and
// the SQL around it are generated by the source module
// (src/lib/pipelineSources/duckDbReader.ts) and parsed back by it, so what the
// picker offers and what the config can hold are one decision. Hand-editing
// the query in the JSON editor keeps the pipeline there, as everywhere else.
//
// The Drive variant differs in one field and one label: it takes a file id
// rather than a URL, because the consent grants `drive.file` — access to the
// files the customer picks, not to the folders around them, so a path resolves
// to nothing. Pasting the Drive URL is fine; the id is taken out of it.
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { sourceForKey, toDriveId, type PipelineForm } from '../../../lib/pipelineSources'
import Select from '../../ui/Select.vue'

const props = defineProps<{
    form: PipelineForm
    fieldErrors: Record<string, string>
}>()

const { t } = useI18n()

const source = computed(() => sourceForKey(props.form.sourceKey))
const isDrive = computed(() => source.value.reader?.address === 'drive')

const readerOptions = computed(() =>
    (source.value.reader?.functions ?? []).map((f) => ({ value: f.fn, label: t(f.labelKey) })),
)

// What the config will actually name, shown under the field: a Drive URL
// pasted whole becomes an id here, in front of the user, rather than silently
// on save.
const resolved = computed(() => (isDrive.value ? toDriveId(props.form.readerUrl) : ''))
</script>

<template>
    <div class="col-span-full">
        <label class="mb-1.5 block text-[12.5px] font-semibold" style="color: var(--ink-2)">
            {{ isDrive ? t('pipelinesUi.wizard.configure.duckdb.driveFile') : t('pipelinesUi.wizard.configure.duckdb.fileUrl') }}
        </label>
        <input
            v-model="form.readerUrl"
            :placeholder="
                isDrive
                    ? t('pipelinesUi.wizard.configure.duckdb.driveFilePlaceholder')
                    : t('pipelinesUi.wizard.configure.duckdb.fileUrlPlaceholder')
            "
            class="h-10 w-full rounded-[10px] border px-[13px] font-mono text-[13px] outline-none"
            style="background: var(--surface-2); border-color: var(--line); color: var(--ink)"
        />
        <p v-if="isDrive && resolved" class="mt-1.5 font-mono text-[11.5px]" style="color: var(--ink-3)">
            gdrive://id:{{ resolved }}
        </p>
        <p v-else-if="isDrive" class="mt-1.5 text-xs leading-[1.5]" style="color: var(--ink-3)">
            {{ t('pipelinesUi.wizard.configure.duckdb.driveFileHint') }}
        </p>
    </div>

    <div>
        <label class="mb-1.5 block text-[12.5px] font-semibold" style="color: var(--ink-2)">
            {{ t('pipelinesUi.wizard.configure.duckdb.readAs') }}
        </label>
        <Select v-model="form.readerFn" :options="readerOptions" />
    </div>

    <div>
        <label class="mb-1.5 block text-[12.5px] font-semibold" style="color: var(--ink-2)">
            {{ t('pipelinesUi.wizard.configure.duckdb.tableName') }}
        </label>
        <input
            v-model="form.readerTable"
            :placeholder="t('pipelinesUi.wizard.configure.duckdb.tableNamePlaceholder')"
            class="h-10 w-full rounded-[10px] border px-[13px] font-mono text-[13px] outline-none"
            style="background: var(--surface-2); border-color: var(--line); color: var(--ink)"
        />
        <p v-if="fieldErrors.tables" class="mt-1.5 text-xs" style="color: var(--err)">{{ fieldErrors.tables }}</p>
    </div>
</template>
